### ISSUE TITLE
pip installation of aimsgb not giving the same as your homepage

### ISSUE THREAD

**Issue by AleksBL** [ksyang2013/aimsgb#1]
Hi im trying to do some graphene grain boundary calculations, and your program seemed fit to do so, but I have encountered some strange behavior of your python code. When comparing the results from your webpage and the python package (installed with pip), the results with the same values of sigma, rotation axis, GB-plane do not agree. The lattices from the python code do not seem to be hexagonal anymore and overall seems twisted.

**Comment by jic198** [comment]
Hi,

Thanks for letting us know the issue. Could you tell me the GB you are
trying to build? Input structure, sigma, rotation axis, etc. I am trying to
reproduce the inconsistency.

Thanks,
Jianli

**Comment by AleksBL** [comment]
Hi,

Here is the python-script Im running together with two pictures of the two resulting outputs from the python module and your website. I have put sigma = 5, rotation axis=[001] and GB plane to [2 -1 0] in both cases. The code generates the initial .fdf file using something called "sisl" which can be installed with pip in python. If you want it try this, then just install sisl. The top of the python script is just functions for making fdf to xsf and such things, the setup happens from line 112.


Best regards,

Aleksander Bach Lorentzen, PhD student at DTU

________________________________
Fra: Jianli Cheng <notifications@github.com>
Sendt: 15. december 2020 23:43:46
Til: ksyang2013/aimsgb
Cc: Aleksander Lorentzen; Author
Emne: Re: [ksyang2013/aimsgb] pip installation of aimsgb not giving the same as your homepage (#1)


Hi,

Thanks for letting us know the issue. Could you tell me the GB you are
trying to build? Input structure, sigma, rotation axis, etc. I am trying to
reproduce the inconsistency.

Thanks,
Jianli

**Comment by AleksBL** [comment]
I of course forgot to put the file in the previous mail.


________________________________
Fra: Aleksander Lorentzen
Sendt: 16. december 2020 08:39:00
Til: ksyang2013/aimsgb; ksyang2013/aimsgb
Cc: Author
Emne: Sv: [ksyang2013/aimsgb] pip installation of aimsgb not giving the same as your homepage (#1)


Hi,

Here is the python-script Im running together with two pictures of the two resulting outputs from the python module and your website. I have put sigma = 5, rotation axis=[001] and GB plane to [2 -1 0] in both cases. The code generates the initial .fdf file using something called "sisl" which can be installed with pip in python. If you want it try this, then just install sisl. The top of the python script is just functions for making fdf to xsf and such things, the setup happens from line 112.


Best regards,

Aleksander Bach Lorentzen, PhD student at DTU

________________________________
Fra: Jianli Cheng <notifications@github.com>
Sendt: 15. december 2020 23:43:46
Til: ksyang2013/aimsgb
Cc: Aleksander Lorentzen; Author
Emne: Re: [ksyang2013/aimsgb] pip installation of aimsgb not giving the same as your homepage (#1)


Hi,

Thanks for letting us know the issue. Could you tell me the GB you are
trying to build? Input structure, sigma, rotation axis, etc. I am trying to
reproduce the inconsistency.

Thanks,
Jianli

**Comment by AleksBL** [comment]
Hi,
I hope my previous emails reached you, but if they didnt here is the input files again

Best regards,
Aleksander
[input_and_pythoncode.tar.gz](https://github.com/ksyang2013/aimsgb/files/5719154/input_and_pythoncode.tar.gz)

**Comment by jic198** [comment]
Hi Aleksander,

I am so sorry for the delayed reply.

I looked at your structure, which is a 2D material. Unfortunately, aimsgb has an issue of creating a GB  for an initial structure like that. The created GB is skewed. I have always hoped to fix this problem, but don't get the time to do that. I am sorry for the inconvenience. 

Thanks,
Jianli

**Comment by jic198** [comment]
The recently updated code should be able to generate a graphene grain boundary structure. An example can be found [here](https://aimsgb-docs.readthedocs.io/en/latest/python/Graphene.html).
