### ISSUE TITLE
rotation axis with negative value

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [ksyang2013/aimsgb#14]
I want to construct SrTiO3 Σ3 (111)[-110] grain boundary. It seems like aimsgb do not support negative value rotation axis. How to solve this problem? I hope you cangive me some guide.

**Comment by jic198** [comment]
Our code supports negative value in rotation axis. But you need to write the python code to that. Instructions can be found here: https://aimsgb-docs.readthedocs.io/en/latest/python/SrTiO3.html In the example, the GB plane should be either one of ['1 1 0', '0 0 -1', '-1 1 0']. So there is no (111) GB plane. Also, I think you don't need the values in rotation axis to be negative, as GB from [-110] would be the same with that from [110].
