### ISSUE TITLE
how to combine the source code to your script?

### ISSUE THREAD

**Issue by Weimin1029** [ksyang2013/aimsgb#3]
hi, 
  I've want to build the twin GB through aimsgb, and read the introduction and you script, But I am not sure how to combine the two to build simple structure. the script are following :
from aimsgb import GrainBoundary, Grain, GBInformation
initial_struct = Grain.from_file("POSCAR_Co2VGa")
axis = [0, 0, 1]
are used in python, it would have some error like def the GrainBoundary, Grain, GBInformation, but  I can't find that def in your script. How could I use that in python through your script? where can I change the structure ?
thanks for your reading and looking forward to your reply.
Best Wishes.

**Comment by jic198** [comment]
Hello. I am not sure what your error messages are. Looks like an `ImportError` error. Could you post your screen output here?
